# Github Workflow to build and deploy a docker image to Github Container Registry
name: Publish Docker image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set sha_short
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - run: echo ${{ env.SHA_SHORT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/temporalcli:${{ env.SHA_SHORT }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          context: .
          labels: |
            org.opencontainers.image.title=Temporal CLI
            org.opencontainers.image.description=Temporal CLI
            org.opencontainers.image.authors=Joan Marc Carbo
            org.opencontainers.image.url=https://github.com/jmcarbo/temporalcli-docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/temporalcli:latest
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          context: .
          labels: |
            org.opencontainers.image.title=Temporal CLI
            org.opencontainers.image.description=Temporal CLI
            org.opencontainers.image.authors=Joan Marc Carbo
            org.opencontainers.image.url=https://github.com/jmcarbo/temporalcli-docker